export const GET_ALL_VILLA = "GET_ALL_VILLA"
export const CREATE_VILLA = "CREATE_VILLA"
export const DELETE_VILLA = "DELETE_VILLA"
export const GET_VILLA_BY_ID = "GET_VILLA_BY_ID"
export const UPDATE_VILLA = "UPDATE_VILLA"


export const GET_ALL_HOUSE = "GET_ALL_HOUSE"
export const CREATE_HOUSE = "CREATE_HOUSE"
export const DELETE_HOUSE = "DELETE_HOUSE"
export const GET_HOUSE_BY_ID = "GET_HOUSE_BY_ID"
export const UPDATE_HOUSE = "UPDATE_HOUSE"


export const GET_ALL_ROOM = "GET_ALL_ROOM"
export const CREATE_ROOM = "CREATE_ROOM"
export const DELETE_ROOM = "DELETE_ROOM"
export const GET_ROOM_BY_ID = "GET_ROOM_BY_ID"
export const UPDATE_ROOM = "UPDATE_ROOM"

export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER"
export const CREATE_CUSTOMER = "CREATE_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"

export const GET_ALL_CONTRACT = "GET_ALL_CONTRACT"
export const CREATE_CONTRACT = "CREATE_CONTRACT"
export const DELETE_CONTRACT = "DELETE_CONTRACT"
export const GET_CONTRACT_BY_ID = "GET_CONTRACT_BY_ID"
export const UPDATE_CONTRACT = "UPDATE_CONTRACT"
